### ISSUE TITLE
Pinned Guild Messages

### ISSUE THREAD

**Issue by mattemre** [DinoDevs/GladiatusCrazyAddon#348]
i have an idea. we need to pinned guild messages. sometimes we need a lot. Instead of sharing a message over and over at different times, something like this is very useful.

**Comment by FrutyX** [comment]
But doesn't Vox Logus (Bathouse) exists for such things?

**Comment by GreatApo** [comment]
> But doesn't Vox Logus (Bathouse) exists for such things?

True...

**Comment by mattemre** [comment]
most people don't use the (vox logus) hamam.
You know this too.

**Comment by FrutyX** [comment]
Nonsense, on every server I've played, all useful info was always in Vox Logus for all to see.

If your players are not using it, it's their fault and own mistake. Now to the feature request, I see a different option, one more realistic - add a "Share" button to Vox Logus messages, when you click on it, it will copy the Vox Logus message and send it as a guild message, so you can easily share any messages directly from Vox Logus.

The original idea with "pinned messages" isn't that much possible, because you have to store the message somewhere, and you can't use your browser memory because everyone has to see it (which is the main idea here), it would be only possible with a remote server (with stored messages) and you don't want that, because who will pay for the servers?

**Comment by GramThanos** [comment]
We can mix them maybe. We can add a feature to check Vox Logus (every 1 or 2 hours) for a special message and pin it at the top of the messages (anyone with write access to Vox Logus would be able to pin a message.

But keep in mind that this addon servers the players, not the guilds, so it cant enforce features related to guilds. Additionally, this would most probably be disabled by default as most guilds would not use it (maybe we can propose to the user to enable it if such a message is found when he visits the Vix Logus).

Still, this maybe a bit problematic.

**Comment by mattemre** [comment]
When a new member comes to a guild, he introduces himself on the vox logus. but after that vox logus never looks again. same goes for me. 
GramThanos' idea looks very good

**Comment by GreatApo** [comment]
Go to guild bath room 1, write a post, click the pin button and then submit it (you need to have delete all messages and post rights for the button to show). Based on your refresh interval (in GCA global options, the interval that used to be only for guild applications) the message will show up at the top of the messages.

**Comment by SleepingShadow-bit** [comment]
Really Nice =)

**Comment by FrutyX** [comment]
Eh, a button you say? Maybe I am doing something wrong, no console errors.

![huh](https://user-images.githubusercontent.com/23278552/175819513-27665fbd-e156-4302-b259-51a4d434822c.PNG)

**Comment by GramThanos** [comment]
![oups](https://c.tenor.com/jjHvnU26sHIAAAAC/oups.gif)

**Comment by GreatApo** [comment]
> Eh, a button you say? Maybe I am doing something wrong, no console errors.
> 

That should have worked. The authorization is checking if the messages are more than the delete message links.
`// Check if admin by checking if you can delete all messages
let numberOfMessages = document.getElementById('content').getElementsByTagName('tr').length/4;
let links = document.getElementById('content').getElementsByTagName('a');
let numberOfDeleteLinks = 0;
for (var i=0; i<links.length; i++) {
	let href = links[i].getAttribute('href');
	if ( href.match('&den=') )
		numberOfDeleteLinks++;
}
if(numberOfMessages > numberOfDeleteLinks){
	console.log('[GCA] Not authorized to pin messages');
	return;
}`
Can you test in your console what number the `document.getElementById('content').getElementsByTagName('tr').length/4` gives you compared to the delete links found (code in the loop)?

**Comment by FrutyX** [comment]
It always give me the right number of delete buttons that exist, if I understand you right.

**Comment by SleepingShadow-bit** [comment]
What u mean about "you need to have delete all messages..."
I don't delete message and i see the pin and works.
![Uploading IMG_20220626_171146.jpg…]()

**Comment by FrutyX** [comment]
I got confused about that part too :D.

**Comment by GreatApo** [comment]
Sorry, I rephrased that: if you can post and you can delete any post, then the button will appear
I am basically trying to recognize if the player is an "admin" or has more rights than a normal member (delete posts)

The last commit post on the console if you have no rights

**Comment by FrutyX** [comment]
You sure it will work for me where there are no other messages from other players, only from me, so GCA isn't sure about it?

That's probably why it does not show, solo guild, so it's not a bug + you probably don't need to pin messages in a one man guild.

**Comment by GreatApo** [comment]
> You sure it will work for me where there are no other messages from other players, only from me, so GCA isn't sure about it?
> 
> That's probably why it does not show, solo guild, so it's not a bug + you probably don't need to pin messages in a one man guild.

It should have been working. Do you get the no authorization in the console.log? Send me the page source code...

**Comment by FrutyX** [comment]
Nothing in the console, I've checked the source code before, there is nothing about the button, it does not exist.

**Comment by GreatApo** [comment]
> Nothing in the console, I've checked the source code before, there is nothing about the button, it does not exist.

I have pushed a commit. If there is nothing, it's something else

**Comment by FrutyX** [comment]
Yes, I always update the folder to the latest commit. I am not aware why it's not showing tho.

**Comment by GreatApo** [comment]
> Yes, I always update the folder to the latest commit. I am not aware why it's not showing tho.

Email me the html source code

**Comment by FrutyX** [comment]
I have a better idea, have you tried using Google Chrome (v103)?

**Comment by SleepingShadow-bit** [comment]
I have now deleted the Badehaus message. My countdown is at 2 minutes. Now after 15 minutes the message is still visible in the guild mail page!

**Comment by SleepingShadow-bit** [comment]
> I have a better idea, have you tried using Google Chrome (v103)?

Now i am on v103. Pin Button is visible and the feature works

**Comment by GreatApo** [comment]
@SleepingShadow-bit I fixed the mentioned problems. @FrutyX I have no idea why it doesn't work for you

**Comment by FrutyX** [comment]
Interesting.

So I tried Edge for example, it works there, I even uploaded my config with settings, it works.

I cleared all cookies and data including Gladiatus ones in Chrome, it still does not work. So I went to check Chrome Canary (it's the development version of Chrome, currently running on v105), even uploaded my config file and it works.

Why it does not show in my current stable Chrome version was simply a miracle for me. I tried all the basic stuff.

I have deleted the extension completely from the browser and added it back, it loaded...

So, it was on my side, but this is the first time I encountered this, every time I test some new commits, I just get the source folder and fully replace my old one, it appears it does not worked this time and it needed to be completely removed/added.

Good experience, next time I'll know, sorry for the troubles.

**Comment by GramThanos** [comment]
Some parts of the extension are updated as soon as you change its file (e.g. each page's script). Other parts need (e.g. script loader) are reloaded when you reload the extension (restart browser).

Your browser may cached a script. Its always good to clear the cache after loading new code. Furthermore, you can clear temporary data form the addon's settings (this may reset some timers).

**Comment by FrutyX** [comment]
By the way, if you write normally, it's fine, but if you write it like an idiot, it's not complete, but perhaps if someone wanted to show something like a bulleted list of something, it will not work.

Nothing serious, but if you want to address it...

Watch:

![msg](https://user-images.githubusercontent.com/23278552/175837610-433ba8dc-abc8-4d1b-81ac-ce74f7b1a40c.PNG)
![msg2](https://user-images.githubusercontent.com/23278552/175837614-0e654c25-d330-4554-8753-23223c1a0e1f.PNG)

**Comment by FrutyX** [comment]
> Some parts of the extension are updated as soon as you change its file (e.g. each page's script). Other parts need (e.g. script loader) are reloaded when you reload the extension (restart browser).
> 
> Your browser may cached a script. Its always good to clear the cache after loading new code. Furthermore, you can clear temporary data form the addon's settings (this may reset some timers).

That's like the most generic answer that some support staff would write to you, did you even read what I wrote? I did restart the browser, I did cleared GCA&Gladiatus cookies, cache and data, that's why it is a miracle to me. And yes, I even tried it via GCA settings.

**Comment by GramThanos** [comment]
Yes, I read your message. Sorry for not specifing it, my reply was more some general info and guessing on what may affect the behavior. I am as confused as you.

**Comment by FrutyX** [comment]
That's fine @GramThanos, don't get me wrong - thank you for trying to help anyway, not sure what went wrong, but it's gone now.

**Comment by GreatApo** [comment]
Thanos is right. I completely forgot that the baths.js was a new file and you need to refresh the addon so that is is recognized and it is loaded.

Well spot Thanos.

**Comment by SleepingShadow-bit** [comment]
If I missed it then sorry....

Is it possible to post a text with a paragraph as a pinned message?
![Screenshot_19](https://user-images.githubusercontent.com/8767665/176020721-64daaf08-71f9-4079-a539-b98bda78268b.png)

![Screenshot_18](https://user-images.githubusercontent.com/8767665/176020738-ff3c00a4-7283-41cb-b9ca-b37f34873f8c.png)

**Comment by GreatApo** [comment]
> If I missed it then sorry....
> 
> Is it possible to post a text with a paragraph as a pinned message?

Fixed

**Comment by SleepingShadow-bit** [comment]
Thanks a lot. It works very well

**Comment by SleepingShadow-bit** [comment]
I would like to pass on a thank you from my guild members here. The feature is very well received!

**Comment by FrutyX** [comment]
Apo The Great 💪

**Comment by mattemre** [comment]
even though I removed the message from the bathouse, still looks on message panel. 
I've been waiting for 2-3 hours, 
![image](https://user-images.githubusercontent.com/95325400/176735792-ec7fa130-3f8e-45ee-afc8-e853157c3fea.png)

**Comment by SleepingShadow-bit** [comment]
Had the problem too and got it fixed (https://github.com/DinoDevs/GladiatusCrazyAddon/issues/348#issuecomment-1166598111 + https://github.com/DinoDevs/GladiatusCrazyAddon/issues/348#issuecomment-1166655486) . 

Do you have the current version?  Also doesn't it work with 1 minute (for testing)?
Clear your gca addon cache and try again

**Comment by FrutyX** [comment]
I've checked it too and it has been fixed

Download it again with the latest commit, set it to 1 min for testing purposes and see if it's okay, if that does not work you can try deleting your gca data like Shadow said, as a last resort you can delete the extension from your browser completely and add it back again.

**Comment by mattemre** [comment]
uninstalling and reinstalling solved my problem

**Comment by SleepingShadow-bit** [comment]
Do you think it is possible to directly link a pinned hyperlink.  As in the guild mails (see screen)

![IMG_20220705_212855](https://user-images.githubusercontent.com/8767665/177401472-3656685d-d403-497a-bae8-faf01d47c4a7.jpg)

**Comment by FrutyX** [comment]
Also, the pin/unpin is only showing when creating a new message, but it's not showing when you are editing already existing message, so for example, if you want to remove your current pin, but not the message, you delete the symbol manually.

But maybe it's on purpose, I don't know.

**Comment by SleepingShadow-bit** [comment]
I think its ok. Because the pin/unpin button is only there to automatically insert the symbol [⚲].  If I edit the amount, I remove the symbol [⚲] and the pin is gone.  And I can manually add the pin again at any time.  Or do I misunderstand you

**Comment by FrutyX** [comment]
I see Apo added it, he scripted it from scratch and made it work in messages, thus I did not seen a reason why it should not be enabled while editing too.

**Comment by GreatApo** [comment]
> Do you think it is possible to directly link a pinned hyperlink. As in the guild mails (see screen)
> 

![image](https://user-images.githubusercontent.com/9620510/177427537-f9db4a66-71ac-4a59-8097-45222be7bd38.png)

**Comment by SleepingShadow-bit** [comment]
Would it be possible to add a paragraph after the nickname for the sake of clarity?

![IMG_20220812_133047](https://user-images.githubusercontent.com/8767665/184346082-7acd5dd3-ee6b-43e5-9029-665b7789658f.jpg)

**Comment by SleepingShadow-bit** [comment]
Does anyone know if my last comment was still implemented?

**Comment by GramThanos** [comment]
I don't think so. We have to move it to a new issue.
